package _07gestaoacademica;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

public class CampoFormularioProfessorComLabel extends javax.swing.JPanel {

    //Atributos
    Icon mostrarIcon = new ImageIcon(getClass().getResource("/_07gestaoacademica/images/mostrar.png"));
    Icon ocultarIcon = new ImageIcon(getClass().getResource("/_07gestaoacademica/images/ocultar.png"));
    Icon iconeAtual = ocultarIcon;
    
    public CampoFormularioProfessorComLabel(JButton botao) {
        initComponents();
        senhaPasswordField.setEchoChar((char) 0);
        
        senhaPasswordField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER) {
                    botao.doClick();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new _07gestaoacademica.CampoDeEscrita();
        cpfLabel = new javax.swing.JLabel();
        cpfTextField = new _07gestaoacademica.CampoDeEscrita();
        telefoneLabel = new javax.swing.JLabel();
        telefoneTextField = new _07gestaoacademica.CampoDeEscrita();
        enderecoLabel = new javax.swing.JLabel();
        enderecoTextField = new _07gestaoacademica.CampoDeEscrita();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new _07gestaoacademica.CampoDeEscrita();
        senhaLabel = new javax.swing.JLabel();
        senhaPasswordField = new javax.swing.JPasswordField();
        mostrarSenhaButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nomeLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(36, 53, 61));
        nomeLabel.setText("Nome:");

        nomeTextField.setText("Digite seu nome");
        nomeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeTextFieldFocusLost(evt);
            }
        });
        nomeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeTextFieldKeyPressed(evt);
            }
        });

        cpfLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(36, 53, 61));
        cpfLabel.setText("CPF:");

        cpfTextField.setText("Digite seu CPF");
        cpfTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusLost(evt);
            }
        });
        cpfTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpfTextFieldKeyPressed(evt);
            }
        });

        telefoneLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        telefoneLabel.setForeground(new java.awt.Color(36, 53, 61));
        telefoneLabel.setText("Telefone:");

        telefoneTextField.setText("Digite seu telefone");
        telefoneTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefoneTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneTextFieldFocusLost(evt);
            }
        });
        telefoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefoneTextFieldKeyPressed(evt);
            }
        });

        enderecoLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        enderecoLabel.setForeground(new java.awt.Color(36, 53, 61));
        enderecoLabel.setText("Endereço:");

        enderecoTextField.setText("Digite seu endereço");
        enderecoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enderecoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enderecoTextFieldFocusLost(evt);
            }
        });
        enderecoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enderecoTextFieldKeyPressed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(36, 53, 61));
        emailLabel.setText("Email:");

        emailTextField.setText("Digite seu email");
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyPressed(evt);
            }
        });

        senhaLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(36, 53, 61));
        senhaLabel.setText("Senha:");

        senhaPasswordField.setBackground(new java.awt.Color(234, 234, 234));
        senhaPasswordField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        senhaPasswordField.setForeground(new java.awt.Color(81, 81, 81));
        senhaPasswordField.setText("senha");
        senhaPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(234, 234, 234), 5, true));
        senhaPasswordField.setOpaque(true);
        senhaPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhaPasswordFieldFocusLost(evt);
            }
        });

        mostrarSenhaButton.setBackground(new java.awt.Color(255, 255, 255));
        mostrarSenhaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_07gestaoacademica/images/ocultar.png"))); // NOI18N
        mostrarSenhaButton.setBorder(null);
        mostrarSenhaButton.setBorderPainted(false);
        mostrarSenhaButton.setContentAreaFilled(false);
        mostrarSenhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(nomeLabel)
                .addGap(315, 315, 315)
                .addComponent(cpfLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(telefoneLabel)
                .addGap(297, 297, 297)
                .addComponent(enderecoLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310)
                .addComponent(senhaLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(mostrarSenhaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLabel)
                    .addComponent(cpfLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefoneLabel)
                    .addComponent(enderecoLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel)
                    .addComponent(senhaLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarSenhaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //Métodos para ações
    public Boolean gerarPopUp(PopUp popUp) {

        boolean telefoneNum = telefoneTextField.getText().chars().allMatch(Character::isDigit); //<- vê se o espaço "telefone" é numérico
        boolean cpfNum = cpfTextField.getText().chars().allMatch(Character::isDigit); //<- vê se o espaço "cpf" é numérico
        String[] provedoresEmail = {"@hotmail.com", "@outlook.com", "@gmail.com", "@yahoo.com"};

        if ("Digite seu nome".equals(nomeTextField.getText())) {
            popUp = new PopUp();
            popUp.semNome(nomeTextField);
            return true;
        } else if (nomeTextField.getText().chars().count() < 3) {
            popUp = new PopUp();
            popUp.limiteNumero("nome", 2, nomeTextField);
            return true;
        } else if ("Digite seu CPF".equals(cpfTextField.getText())) {
            popUp = new PopUp();
            popUp.campoNaoPreenchido("CPF", cpfTextField);
            return true;
        } else if ("Digite seu email".equals(emailTextField.getText())) {
            popUp = new PopUp();
            popUp.campoNaoPreenchido("Email", emailTextField);
            return true;
        } else if ("senha".equals(String.valueOf(senhaPasswordField.getPassword()))) {
            popUp = new PopUp();
            popUp.campoNaoPreenchido("Senha", senhaPasswordField);
            return true;
        } else if (!"Digite seu telefone".equals(telefoneTextField.getText()) && !telefoneNum) {
            popUp = new PopUp();
            popUp.naoNumerico("telefone", telefoneTextField);
            return true;
        } else if (!cpfNum) {
            popUp = new PopUp();
            popUp.naoNumerico("CPF", cpfTextField);
            return true;
        } else if (!emailTextField.getText().contains(provedoresEmail[0]) && !emailTextField.getText().contains(provedoresEmail[1]) && !emailTextField.getText().contains(provedoresEmail[2]) && !emailTextField.getText().contains(provedoresEmail[3])) {
            popUp = new PopUp();
            popUp.emailErrado(emailTextField);
            return true;
        } else if (String.valueOf(senhaPasswordField.getPassword()).length() < 8) {
            popUp = new PopUp();
            popUp.limiteNumero("senha", 8, senhaPasswordField);
            return true;
        }
        
        return false;

    }

    protected void campoComFoco(String texto, JTextField textField) {
        if (texto.equals(textField.getText())) {
            textField.setText("");
        } else {
            textField.setForeground(new Color(81, 81, 81));
        }
    }

    protected void campoSemFoco(String texto, JTextField textField) {
        if ("".equals(textField.getText())) {
            textField.setText(texto);
            textField.setForeground(new Color(81, 81, 81));
        } else {
            textField.setForeground(Color.BLACK);
        }
    }

    public void pegaDadosProfessor(UsuarioProfessor professor) {

        professor.setNome(nomeTextField.getText());
        professor.setCpf(cpfTextField.getText());
        professor.setTelefone(telefoneTextField.getText());
        professor.setEndereco(enderecoTextField.getText());
        professor.setEmail(emailTextField.getText());
        professor.setSenha(String.valueOf(senhaPasswordField.getPassword()));
        professor.setMatricula(Usuario.getProximaMatricula());

    }

    protected void pegaDadosAluno(UsuarioAluno aluno) {

        aluno.setNome(nomeTextField.getText());
        aluno.setCpf(cpfTextField.getText());
        aluno.setTelefone(telefoneTextField.getText());
        aluno.setEndereco(enderecoTextField.getText());
        aluno.setEmail(emailTextField.getText());
        aluno.setSenha(String.valueOf(senhaPasswordField.getPassword()));
        aluno.setMatricula(Usuario.getProximaMatricula());

    }

    public void limparCampos() {
        nomeTextField.setText("");
        cpfTextField.setText("");
        telefoneTextField.setText("");
        enderecoTextField.setText("");
        emailTextField.setText("");
        senhaPasswordField.setText("");
    }
    
    public void focarNoCampoNome() {
        nomeTextField.requestFocus();
    }
    
    public void pegarDadosDoUsuario(int linha) {
        
        UsuarioProfessor professorSelecionado = BancoDeDados.retornarProfessores().get(linha);
        
        nomeTextField.setText(professorSelecionado.getNome());
        cpfTextField.setText(professorSelecionado.getCpf());
        telefoneTextField.setText(professorSelecionado.getTelefone());
        enderecoTextField.setText(professorSelecionado.getEndereco());
        emailTextField.setText(professorSelecionado.getEmail());
        senhaPasswordField.setText(professorSelecionado.getSenha());
        
    }
    
    private void nomeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextFieldFocusGained
        campoComFoco("Digite seu nome", nomeTextField);
    }//GEN-LAST:event_nomeTextFieldFocusGained

    private void nomeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextFieldFocusLost
        campoSemFoco("Digite seu nome", nomeTextField);
    }//GEN-LAST:event_nomeTextFieldFocusLost

    private void nomeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        cpfTextField.requestFocus();
    }//GEN-LAST:event_nomeTextFieldKeyPressed

    private void cpfTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusGained
        campoComFoco("Digite seu CPF", cpfTextField);
    }//GEN-LAST:event_cpfTextFieldFocusGained

    private void cpfTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusLost
        campoSemFoco("Digite seu CPF", cpfTextField);
    }//GEN-LAST:event_cpfTextFieldFocusLost

    private void cpfTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        telefoneTextField.requestFocus();
    }//GEN-LAST:event_cpfTextFieldKeyPressed

    private void telefoneTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneTextFieldFocusGained
        campoComFoco("Digite seu telefone", telefoneTextField);
    }//GEN-LAST:event_telefoneTextFieldFocusGained

    private void telefoneTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneTextFieldFocusLost
        campoSemFoco("Digite seu telefone", telefoneTextField);
    }//GEN-LAST:event_telefoneTextFieldFocusLost

    private void telefoneTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        enderecoTextField.requestFocus();
    }//GEN-LAST:event_telefoneTextFieldKeyPressed

    private void enderecoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enderecoTextFieldFocusGained
        campoComFoco("Digite seu endereço", enderecoTextField);
    }//GEN-LAST:event_enderecoTextFieldFocusGained

    private void enderecoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enderecoTextFieldFocusLost
        campoSemFoco("Digite seu endereço", enderecoTextField);
    }//GEN-LAST:event_enderecoTextFieldFocusLost

    private void enderecoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enderecoTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        emailTextField.requestFocus();
    }//GEN-LAST:event_enderecoTextFieldKeyPressed

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        campoComFoco("Digite seu email", emailTextField);
    }//GEN-LAST:event_emailTextFieldFocusGained

    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        campoSemFoco("Digite seu email", emailTextField);
    }//GEN-LAST:event_emailTextFieldFocusLost

    private void emailTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        senhaPasswordField.requestFocus();
    }//GEN-LAST:event_emailTextFieldKeyPressed

    private void senhaPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaPasswordFieldFocusGained
        campoComFoco("senha", senhaPasswordField);
        senhaPasswordField.setEchoChar((char) '*');
    }//GEN-LAST:event_senhaPasswordFieldFocusGained

    private void senhaPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaPasswordFieldFocusLost
        campoSemFoco("senha", senhaPasswordField);
        if ("senha".equals(String.valueOf(senhaPasswordField.getPassword())))
        senhaPasswordField.setEchoChar((char) 0);
    }//GEN-LAST:event_senhaPasswordFieldFocusLost

    private void mostrarSenhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaButtonActionPerformed
        if (iconeAtual == ocultarIcon) {
            mostrarSenhaButton.setIcon(mostrarIcon);
            senhaPasswordField.setEchoChar((char) 0);
            iconeAtual = mostrarIcon;
        } else {
            mostrarSenhaButton.setIcon(ocultarIcon);
            senhaPasswordField.setEchoChar((char) '*');
            iconeAtual = ocultarIcon;
        }
    }//GEN-LAST:event_mostrarSenhaButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpfLabel;
    private _07gestaoacademica.CampoDeEscrita cpfTextField;
    private javax.swing.JLabel emailLabel;
    private _07gestaoacademica.CampoDeEscrita emailTextField;
    private javax.swing.JLabel enderecoLabel;
    private _07gestaoacademica.CampoDeEscrita enderecoTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarSenhaButton;
    private javax.swing.JLabel nomeLabel;
    private _07gestaoacademica.CampoDeEscrita nomeTextField;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JLabel telefoneLabel;
    private _07gestaoacademica.CampoDeEscrita telefoneTextField;
    // End of variables declaration//GEN-END:variables
}
