package _07gestaoacademica;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author ravtec
 */
public class CampoFormularioCoordenador extends javax.swing.JPanel {

    //Atributos
    Icon mostrarIcon = new ImageIcon(getClass().getResource("/_07gestaoacademica/images/mostrar.png"));
    Icon ocultarIcon = new ImageIcon(getClass().getResource("/_07gestaoacademica/images/ocultar.png"));
    Icon iconeAtual = ocultarIcon;
    
    public CampoFormularioCoordenador(JButton botao) {
        
        initComponents();
        senhaPasswordField.setEchoChar((char) 0);
        
        senhaPasswordField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER)
                    pressionarEnterNoCampoSenha(botao);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTextField = new _07gestaoacademica.CampoDeEscrita();
        cpfTextField = new _07gestaoacademica.CampoDeEscrita();
        telefoneTextField = new _07gestaoacademica.CampoDeEscrita();
        enderecoTextField = new _07gestaoacademica.CampoDeEscrita();
        emailTextField = new _07gestaoacademica.CampoDeEscrita();
        nomeUsuarioTextField = new _07gestaoacademica.CampoDeEscrita();
        senhaPasswordField = new javax.swing.JPasswordField();
        mostrarSenhaButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        nomeTextField.setText("Digite seu nome");
        nomeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeTextFieldFocusLost(evt);
            }
        });
        nomeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeTextFieldKeyPressed(evt);
            }
        });

        cpfTextField.setText("Digite seu CPF");
        cpfTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfTextFieldFocusLost(evt);
            }
        });
        cpfTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpfTextFieldKeyPressed(evt);
            }
        });

        telefoneTextField.setText("Digite seu telefone");
        telefoneTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefoneTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneTextFieldFocusLost(evt);
            }
        });
        telefoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefoneTextFieldKeyPressed(evt);
            }
        });

        enderecoTextField.setText("Digite seu endereço");
        enderecoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enderecoTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                enderecoTextFieldFocusLost(evt);
            }
        });
        enderecoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enderecoTextFieldKeyPressed(evt);
            }
        });

        emailTextField.setText("Digite seu email");
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyPressed(evt);
            }
        });

        nomeUsuarioTextField.setText("Digite seu nome de usuário");
        nomeUsuarioTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeUsuarioTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeUsuarioTextFieldFocusLost(evt);
            }
        });
        nomeUsuarioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeUsuarioTextFieldKeyPressed(evt);
            }
        });

        senhaPasswordField.setBackground(new java.awt.Color(234, 234, 234));
        senhaPasswordField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        senhaPasswordField.setForeground(new java.awt.Color(81, 81, 81));
        senhaPasswordField.setText("senha");
        senhaPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(234, 234, 234), 5, true));
        senhaPasswordField.setOpaque(true);
        senhaPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                senhaPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                senhaPasswordFieldFocusLost(evt);
            }
        });

        mostrarSenhaButton.setBackground(new java.awt.Color(255, 255, 255));
        mostrarSenhaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_07gestaoacademica/images/ocultar.png"))); // NOI18N
        mostrarSenhaButton.setBorder(null);
        mostrarSenhaButton.setContentAreaFilled(false);
        mostrarSenhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeUsuarioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(senhaPasswordField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrarSenhaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefoneTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(telefoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostrarSenhaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(nomeUsuarioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(senhaPasswordField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    //Métodos de simplificação
    public Boolean gerarPopUp(PopUp popUp) {
        
        boolean telefoneNum = telefoneTextField.getText().chars().allMatch(Character::isDigit); //<- vê se o espaço "telefone" é numérico
        boolean cpfNum = cpfTextField.getText().chars().allMatch(Character::isDigit); //<- vê se o espaço "cpf" é numérico
        String[] provedoresEmail = {"@hotmail.com", "@outlook.com", "@gmail.com", "@yahoo.com"};
        
        if("Digite seu nome".equals(nomeTextField.getText())) {
            popUp = new PopUp();
            popUp.semNome(nomeTextField);
            return true;
        } else if(nomeTextField.getText().chars().count() < 3) {
            popUp = new PopUp();
            popUp.limiteNumero("nome", 2, nomeTextField);
            return true;
        } else if("Digite seu CPF".equals(cpfTextField.getText())) {
            popUp = new PopUp();
            popUp.campoNaoPreenchido("CPF", cpfTextField);
            return true;
        } else if("Digite seu email".equals(emailTextField.getText())) {
            popUp = new PopUp();
            popUp.campoNaoPreenchido("Email", emailTextField);
            return true;
        } else if("senha".equals(String.valueOf(senhaPasswordField.getPassword()))) {
            popUp = new PopUp();
            popUp.campoNaoPreenchido("Senha", senhaPasswordField);
            return true;
        } else if(!"Digite seu telefone".equals(telefoneTextField.getText()) && !telefoneNum) {
            popUp = new PopUp();
            popUp.naoNumerico("telefone", telefoneTextField);
            return true;
        } else if(!cpfNum) {
            popUp = new PopUp();
            popUp.naoNumerico("CPF", cpfTextField);
            return true;
        } else if(!emailTextField.getText().contains(provedoresEmail[0]) && !emailTextField.getText().contains(provedoresEmail[1]) && !emailTextField.getText().contains(provedoresEmail[2]) && !emailTextField.getText().contains(provedoresEmail[3])) {
            popUp = new PopUp();
            popUp.emailErrado(emailTextField);
            return true;
        } else if(String.valueOf(senhaPasswordField.getPassword()).length() < 8) {
            popUp = new PopUp();
            popUp.limiteNumero("senha", 8, senhaPasswordField);
            return true;
        } else if("Digite seu nome de usuário".equals(nomeUsuarioTextField.getText())) {
            popUp = new PopUp();
            popUp.nomeUsuario(nomeUsuarioTextField);
            return true;
        }
        
        return false;

    }
    
    protected void campoComFoco(String texto, JTextField textField) {
        if(texto.equals(textField.getText()))
            textField.setText("");
        else
            textField.setForeground(new Color(81, 81, 81));
    }
    
    protected void campoSemFoco(String texto, JTextField textField) {
        if("".equals(textField.getText())) {
            textField.setText(texto);
            textField.setForeground(new Color(81, 81, 81));
        }
        else
            textField.setForeground(Color.BLACK);
    }
    
    public void pegaDados(UsuarioCoordenador coordenador) {
        
        coordenador.setNome(nomeTextField.getText());
        coordenador.setCpf(cpfTextField.getText());
        coordenador.setTelefone(telefoneTextField.getText());
        coordenador.setEndereco(enderecoTextField.getText());
        coordenador.setEmail(emailTextField.getText());
        coordenador.setSenha(String.valueOf(senhaPasswordField.getPassword()));
        coordenador.setNomeUsuario(nomeUsuarioTextField.getText());
        
    }
    
    public void limparCampos() {
        nomeTextField.setText("");
        cpfTextField.setText("");
        telefoneTextField.setText("");
        enderecoTextField.setText("");
        emailTextField.setText("");
        nomeUsuarioTextField.setText("");
        senhaPasswordField.setText("");
    }
    
    public void focarNoCampoNome() {
        nomeTextField.requestFocus();
    }
    
    
    //Métodos de ação
    private void senhaPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaPasswordFieldFocusGained
        campoComFoco("senha", senhaPasswordField);
        senhaPasswordField.setEchoChar((char) '*');
    }//GEN-LAST:event_senhaPasswordFieldFocusGained

    private void senhaPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_senhaPasswordFieldFocusLost
        campoSemFoco("senha", senhaPasswordField);
        if ("senha".equals(String.valueOf(senhaPasswordField.getPassword())))
            senhaPasswordField.setEchoChar((char) 0);
    }//GEN-LAST:event_senhaPasswordFieldFocusLost

    private void mostrarSenhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaButtonActionPerformed
       if(iconeAtual == ocultarIcon) {
            mostrarSenhaButton.setIcon(mostrarIcon);
            senhaPasswordField.setEchoChar((char) 0);
            iconeAtual = mostrarIcon;
        } else{
            mostrarSenhaButton.setIcon(ocultarIcon);
            senhaPasswordField.setEchoChar((char) '*');
            iconeAtual = ocultarIcon;
        }
    }//GEN-LAST:event_mostrarSenhaButtonActionPerformed

    private void nomeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextFieldFocusGained
        campoComFoco("Digite seu nome", nomeTextField);
    }//GEN-LAST:event_nomeTextFieldFocusGained

    private void nomeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeTextFieldFocusLost
        campoSemFoco("Digite seu nome", nomeTextField);
    }//GEN-LAST:event_nomeTextFieldFocusLost

    private void cpfTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusGained
        campoComFoco("Digite seu CPF", cpfTextField);
    }//GEN-LAST:event_cpfTextFieldFocusGained

    private void cpfTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfTextFieldFocusLost
        campoSemFoco("Digite seu CPF", cpfTextField);
    }//GEN-LAST:event_cpfTextFieldFocusLost

    private void telefoneTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneTextFieldFocusGained
        campoComFoco("Digite seu telefone", telefoneTextField);
    }//GEN-LAST:event_telefoneTextFieldFocusGained

    private void telefoneTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneTextFieldFocusLost
        campoSemFoco("Digite seu telefone", telefoneTextField);
    }//GEN-LAST:event_telefoneTextFieldFocusLost

    private void enderecoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enderecoTextFieldFocusGained
        campoComFoco("Digite seu endereço", enderecoTextField);
    }//GEN-LAST:event_enderecoTextFieldFocusGained

    private void enderecoTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enderecoTextFieldFocusLost
        campoSemFoco("Digite seu endereço", enderecoTextField);
    }//GEN-LAST:event_enderecoTextFieldFocusLost

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        campoComFoco("Digite seu email", emailTextField);
    }//GEN-LAST:event_emailTextFieldFocusGained

    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        campoSemFoco("Digite seu email", emailTextField);
    }//GEN-LAST:event_emailTextFieldFocusLost

    private void nomeUsuarioTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeUsuarioTextFieldFocusGained
        campoComFoco("Digite seu nome de usuário", nomeUsuarioTextField);
    }//GEN-LAST:event_nomeUsuarioTextFieldFocusGained

    private void nomeUsuarioTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeUsuarioTextFieldFocusLost
        campoSemFoco("Digite seu nome de usuário", nomeUsuarioTextField);
    }//GEN-LAST:event_nomeUsuarioTextFieldFocusLost

    private void nomeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            cpfTextField.requestFocus();
    }//GEN-LAST:event_nomeTextFieldKeyPressed

    private void cpfTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            telefoneTextField.requestFocus();
    }//GEN-LAST:event_cpfTextFieldKeyPressed

    private void telefoneTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            enderecoTextField.requestFocus();
    }//GEN-LAST:event_telefoneTextFieldKeyPressed

    private void enderecoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enderecoTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            emailTextField.requestFocus();
    }//GEN-LAST:event_enderecoTextFieldKeyPressed

    private void emailTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            nomeUsuarioTextField.requestFocus();
    }//GEN-LAST:event_emailTextFieldKeyPressed

    private void nomeUsuarioTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeUsuarioTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            senhaPasswordField.requestFocus();
    }//GEN-LAST:event_nomeUsuarioTextFieldKeyPressed

    public void pressionarEnterNoCampoSenha(JButton botao) {
        botao.doClick();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private _07gestaoacademica.CampoDeEscrita cpfTextField;
    private _07gestaoacademica.CampoDeEscrita emailTextField;
    private _07gestaoacademica.CampoDeEscrita enderecoTextField;
    private javax.swing.JButton mostrarSenhaButton;
    private _07gestaoacademica.CampoDeEscrita nomeTextField;
    private _07gestaoacademica.CampoDeEscrita nomeUsuarioTextField;
    private javax.swing.JPasswordField senhaPasswordField;
    private _07gestaoacademica.CampoDeEscrita telefoneTextField;
    // End of variables declaration//GEN-END:variables
}
