package _07gestaoacademica;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author ruben-braga
 */
public class FormularioContaUsuario extends javax.swing.JFrame {

    //Atributos
    private int mouseX, mouseY;
    public FormularioContaUsuario esseFormulario = this;
    GestaoContaUsuario novaGestaoContaUsuario;
    PopUp popUp;
    CampoFormularioCoordenador formularioCoordenador;
    CampoFormularioProfessor formularioProfessor;
    UsuarioCoordenador coordenador;
    UsuarioProfessor professor;
    UsuarioAluno aluno;

    public FormularioContaUsuario() {
        initComponents();
        formularioCoordenador = new CampoFormularioCoordenador(criarContaButton);
        jScrollPane1.setViewportView(formularioCoordenador); //adiciona Panel visual mesmo depois de construido 
        formularioCoordenador.focarNoCampoNome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        formularioGeralPanel = new javax.swing.JPanel();
        cabecalhoPanel = new javax.swing.JPanel();
        tituloCabecalhoLabel = new javax.swing.JLabel();
        sairPaginaButton = new javax.swing.JButton();
        coordenadorRadioButton = new javax.swing.JRadioButton();
        professorRadioButton = new javax.swing.JRadioButton();
        alunoRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        entrarContaButton = new _07gestaoacademica.CustomizacaoBotao();
        identifiqueLabel1 = new javax.swing.JLabel();
        criarContaButton = new _07gestaoacademica.CustomizacaoBotao();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Conta");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        formularioGeralPanel.setBackground(new java.awt.Color(255, 255, 255));

        cabecalhoPanel.setBackground(new java.awt.Color(255, 255, 255));
        cabecalhoPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cabecalhoPanelMouseDragged(evt);
            }
        });
        cabecalhoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cabecalhoPanelMousePressed(evt);
            }
        });

        tituloCabecalhoLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        tituloCabecalhoLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloCabecalhoLabel.setText("CRIAR CONTA");

        sairPaginaButton.setBackground(new java.awt.Color(255, 255, 255));
        sairPaginaButton.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        sairPaginaButton.setForeground(new java.awt.Color(0, 0, 0));
        sairPaginaButton.setText("X");
        sairPaginaButton.setBorder(null);
        sairPaginaButton.setContentAreaFilled(false);
        sairPaginaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sairPaginaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairPaginaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairPaginaButtonMouseExited(evt);
            }
        });
        sairPaginaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairPaginaButtonActionPerformed(evt);
            }
        });

        coordenadorRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(coordenadorRadioButton);
        coordenadorRadioButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        coordenadorRadioButton.setForeground(new java.awt.Color(36, 53, 61));
        coordenadorRadioButton.setSelected(true);
        coordenadorRadioButton.setText("Sou Coordenador(a)");
        coordenadorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordenadorRadioButtonActionPerformed(evt);
            }
        });

        professorRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(professorRadioButton);
        professorRadioButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        professorRadioButton.setForeground(new java.awt.Color(36, 53, 61));
        professorRadioButton.setText("Sou Professor(a)");
        professorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorRadioButtonActionPerformed(evt);
            }
        });

        alunoRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(alunoRadioButton);
        alunoRadioButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        alunoRadioButton.setForeground(new java.awt.Color(36, 53, 61));
        alunoRadioButton.setText("Sou Aluno(a)");
        alunoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoRadioButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(76, 95, 99));

        javax.swing.GroupLayout cabecalhoPanelLayout = new javax.swing.GroupLayout(cabecalhoPanel);
        cabecalhoPanel.setLayout(cabecalhoPanelLayout);
        cabecalhoPanelLayout.setHorizontalGroup(
            cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                        .addComponent(coordenadorRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(professorRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alunoRadioButton)
                        .addContainerGap(348, Short.MAX_VALUE))
                    .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                        .addComponent(tituloCabecalhoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sairPaginaButton)
                        .addGap(17, 17, 17))))
        );
        cabecalhoPanelLayout.setVerticalGroup(
            cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCabecalhoLabel)
                    .addComponent(sairPaginaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professorRadioButton)
                    .addComponent(alunoRadioButton)
                    .addComponent(coordenadorRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        entrarContaButton.setBackground(new java.awt.Color(102, 102, 102));
        entrarContaButton.setForeground(new java.awt.Color(255, 255, 255));
        entrarContaButton.setText("ENTRE NA SUA CONTA");
        entrarContaButton.setCor(new java.awt.Color(102, 102, 102));
        entrarContaButton.setCorBorda(new java.awt.Color(255, 255, 255));
        entrarContaButton.setCorEntrou(new java.awt.Color(19, 176, 110));
        entrarContaButton.setCorSaiu(new java.awt.Color(102, 102, 102));
        entrarContaButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entrarContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarContaButtonActionPerformed(evt);
            }
        });

        identifiqueLabel1.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        identifiqueLabel1.setForeground(new java.awt.Color(0, 0, 0));
        identifiqueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        identifiqueLabel1.setText("ou");

        criarContaButton.setForeground(new java.awt.Color(255, 255, 255));
        criarContaButton.setText("CRIAR CONTA");
        criarContaButton.setCor(new java.awt.Color(36, 53, 61));
        criarContaButton.setCorBorda(new java.awt.Color(255, 255, 255));
        criarContaButton.setCorEntrou(new java.awt.Color(19, 176, 110));
        criarContaButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        criarContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formularioGeralPanelLayout = new javax.swing.GroupLayout(formularioGeralPanel);
        formularioGeralPanel.setLayout(formularioGeralPanelLayout);
        formularioGeralPanelLayout.setHorizontalGroup(
            formularioGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabecalhoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(formularioGeralPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(formularioGeralPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(entrarContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(identifiqueLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(criarContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        formularioGeralPanelLayout.setVerticalGroup(
            formularioGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioGeralPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(cabecalhoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(formularioGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entrarContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formularioGeralPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(identifiqueLabel1))
                    .addComponent(criarContaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formularioGeralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formularioGeralPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Métodos para ações
    
    public void comecarAcaoDeCriarConta() {
        criarContaButton.doClick();
    }
    
    private void cabecalhoPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabecalhoPanelMousePressed
        mouseX = evt.getX(); //evento de mover a janela
        mouseY = evt.getY();
    }//GEN-LAST:event_cabecalhoPanelMousePressed

    private void cabecalhoPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabecalhoPanelMouseDragged
        this.setLocation(this.getX() + evt.getX() - mouseX, this.getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_cabecalhoPanelMouseDragged

    private void sairPaginaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairPaginaButtonActionPerformed
        mouseX = getX();
        mouseY = getY();
        this.dispose();
        novaGestaoContaUsuario = new GestaoContaUsuario();
        novaGestaoContaUsuario.setLocation(mouseX, mouseY);
        novaGestaoContaUsuario.setVisible(true);
    }//GEN-LAST:event_sairPaginaButtonActionPerformed

    private void sairPaginaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairPaginaButtonMouseEntered
        Color corSelecionado = new Color(89, 89, 89);
        sairPaginaButton.setForeground(corSelecionado);
    }//GEN-LAST:event_sairPaginaButtonMouseEntered

    private void sairPaginaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairPaginaButtonMouseExited
        sairPaginaButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_sairPaginaButtonMouseExited

    private void professorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorRadioButtonActionPerformed
        formularioProfessor = new CampoFormularioProfessor(criarContaButton);
        jScrollPane1.setViewportView(formularioProfessor);
        formularioProfessor.focarNoCampoNome();
    }//GEN-LAST:event_professorRadioButtonActionPerformed

    private void alunoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoRadioButtonActionPerformed
        formularioProfessor = new CampoFormularioProfessor(criarContaButton);
        jScrollPane1.setViewportView(formularioProfessor);
        formularioProfessor.focarNoCampoNome();
    }//GEN-LAST:event_alunoRadioButtonActionPerformed

    private void coordenadorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordenadorRadioButtonActionPerformed
        formularioCoordenador = new CampoFormularioCoordenador(criarContaButton);
        jScrollPane1.setViewportView(formularioCoordenador);
        formularioCoordenador.focarNoCampoNome();
    }//GEN-LAST:event_coordenadorRadioButtonActionPerformed

    private void entrarContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarContaButtonActionPerformed
        novaGestaoContaUsuario = new GestaoContaUsuario();
        novaGestaoContaUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_entrarContaButtonActionPerformed

    private void criarContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaButtonActionPerformed

        if (coordenadorRadioButton.isSelected()) {

            if (!formularioCoordenador.gerarPopUp(popUp)) {

                coordenador = new UsuarioCoordenador();
                formularioCoordenador.pegaDados(coordenador);
                BancoDeDados.cadastrarUsuario(coordenador);

                popUp = new PopUp();
                popUp.mensagemFinalDoCadastroInicial("Sua conta foi criada com sucesso! Acesse o sistema.", esseFormulario);
                formularioCoordenador.limparCampos();

            }

        } else if (professorRadioButton.isSelected()) {

            if (!formularioProfessor.gerarPopUp(popUp)) {

                professor = new UsuarioProfessor();
                formularioProfessor.pegaDadosProfessor(professor);
                BancoDeDados.cadastrarUsuario(professor);

                popUp = new PopUp();
                popUp.mensagemFinalDoCadastroInicial("Sua conta foi criada com sucesso! Sua matrícula é " + professor.getMatricula() + ".", esseFormulario);
                formularioProfessor.limparCampos();

            }

        } else {

            if (!formularioProfessor.gerarPopUp(popUp)) {

                aluno = new UsuarioAluno();
                formularioProfessor.pegaDadosAluno(aluno);
                BancoDeDados.cadastrarUsuario(aluno);

                popUp = new PopUp();
                popUp.mensagemFinalDoCadastroInicial("Sua conta foi criada com sucesso! Sua matrícula é " + aluno.getMatricula() + ".", esseFormulario);
                formularioProfessor.limparCampos();

            }

        }

    }//GEN-LAST:event_criarContaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public FormularioContaUsuario(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioContaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alunoRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cabecalhoPanel;
    private javax.swing.JRadioButton coordenadorRadioButton;
    private _07gestaoacademica.CustomizacaoBotao criarContaButton;
    private _07gestaoacademica.CustomizacaoBotao entrarContaButton;
    private javax.swing.JPanel formularioGeralPanel;
    private javax.swing.JLabel identifiqueLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton professorRadioButton;
    private javax.swing.JButton sairPaginaButton;
    private javax.swing.JLabel tituloCabecalhoLabel;
    // End of variables declaration//GEN-END:variables
}
