package _07gestaoacademica;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.Action;

/**
 *
 * @author ruben-braga
 */
public class FormularioContaUsuario extends javax.swing.JFrame {

    //Atributos
    private int mouseX, mouseY, numeroMatricula;
    private UsuarioProfessor usuario;
    private PopUp popUp;
    GestaoContaUsuario novaGestaoContaUsuario;
    CampoFormularioCoordenador formularioCoordenador;
    CampoFormularioProfessor formularioProfessor;

    protected void gerarPopUp(CampoFormularioCoordenador formularioCoordenador, CampoFormularioProfessor formularioProfessor) {
        
        /*boolean telefoneNum = telefoneTextField.getText().chars().allMatch(Character::isDigit); //<- vê se o espaço "telefone" é numérico
        boolean cpfNum = cpfTextField.getText().chars().allMatch(Character::isDigit); //<- vê se o espaço "cpf" é numérico
        boolean emailCorreto = emailTextField.getText().contains("@"); //método de verificação se tem ou não @ no campo

        if("".equals(formularioCoordenador)) {
            popUp = new PopUp();
            popUp.semNome();
        } else if("".equals(cpfTextField.getText())) {
            popUp = new PopUp();
            popUp.campoNaoPreenchido("CPF");
        } else if("".equals(emailTextField.getText())) {
            popUp = new PopUp();
            popUp.campoNaoPreenchido("Email");
        } else if("".equals(String.valueOf(senhaPasswordField.getPassword()))) {
            popUp = new PopUp();
            popUp.campoNaoPreenchido("Senha");
        } else if(!"".equals(telefoneTextField.getText()) && !telefoneNum) {
            popUp = new PopUp();
            popUp.naoNumerico("telefone");
        } else if(!cpfNum) {
            popUp = new PopUp();
            popUp.naoNumerico("CPF");
        } else if(!emailCorreto) {
            popUp = new PopUp();
            popUp.emailErrado();
        } else if(nomeTextField.getText().chars().count() < 3) {
            popUp = new PopUp();
            popUp.limiteNumero("nome", 2);
        }*/

    }
    
    public void pegaDados() {
        
        /*String senha = new String(senhaPasswordField.getPassword());
        
        usuario.setNome(nomeTextField.getText());
        usuario.setTelefone(telefoneTextField.getText());
        usuario.setEmail(emailTextField.getText());
        usuario.setCpf(cpfTextField.getText());
        usuario.setEndereco(enderecoTextField.getText());
        usuario.setSenha(senha);*/
        
    }

    public FormularioContaUsuario() {
        initComponents();
        formularioCoordenador = new CampoFormularioCoordenador();
        jScrollPane1.setViewportView(formularioCoordenador); //adiciona Panel visual mesmo depois de construido 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        formularioGeralPanel = new javax.swing.JPanel();
        cabecalhoPanel = new javax.swing.JPanel();
        tituloCabecalhoLabel = new javax.swing.JLabel();
        sairPaginaButton = new javax.swing.JButton();
        coordenadorRadioButton = new javax.swing.JRadioButton();
        professorRadioButton = new javax.swing.JRadioButton();
        alunoRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        criarContaBotton = new _07gestaoacademica.CustomizacaoBotao();
        identifiqueLabel1 = new javax.swing.JLabel();
        entrarContaBotton = new _07gestaoacademica.CustomizacaoBotao();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Conta");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        formularioGeralPanel.setBackground(new java.awt.Color(255, 255, 255));

        cabecalhoPanel.setBackground(new java.awt.Color(255, 255, 255));
        cabecalhoPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cabecalhoPanelMouseDragged(evt);
            }
        });
        cabecalhoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cabecalhoPanelMousePressed(evt);
            }
        });

        tituloCabecalhoLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        tituloCabecalhoLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloCabecalhoLabel.setText("CRIAR CONTA");

        sairPaginaButton.setBackground(new java.awt.Color(255, 255, 255));
        sairPaginaButton.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        sairPaginaButton.setForeground(new java.awt.Color(0, 0, 0));
        sairPaginaButton.setText("X");
        sairPaginaButton.setBorder(null);
        sairPaginaButton.setContentAreaFilled(false);
        sairPaginaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sairPaginaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairPaginaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairPaginaButtonMouseExited(evt);
            }
        });
        sairPaginaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairPaginaButtonActionPerformed(evt);
            }
        });

        coordenadorRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(coordenadorRadioButton);
        coordenadorRadioButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        coordenadorRadioButton.setForeground(new java.awt.Color(36, 53, 61));
        coordenadorRadioButton.setSelected(true);
        coordenadorRadioButton.setText("Sou Coordenador(a)");
        coordenadorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordenadorRadioButtonActionPerformed(evt);
            }
        });

        professorRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(professorRadioButton);
        professorRadioButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        professorRadioButton.setForeground(new java.awt.Color(36, 53, 61));
        professorRadioButton.setText("Sou Professor(a)");
        professorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorRadioButtonActionPerformed(evt);
            }
        });

        alunoRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(alunoRadioButton);
        alunoRadioButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        alunoRadioButton.setForeground(new java.awt.Color(36, 53, 61));
        alunoRadioButton.setText("Sou Aluno(a)");
        alunoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoRadioButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(76, 95, 99));

        javax.swing.GroupLayout cabecalhoPanelLayout = new javax.swing.GroupLayout(cabecalhoPanel);
        cabecalhoPanel.setLayout(cabecalhoPanelLayout);
        cabecalhoPanelLayout.setHorizontalGroup(
            cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                        .addComponent(coordenadorRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(professorRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alunoRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                        .addComponent(tituloCabecalhoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 503, Short.MAX_VALUE)
                        .addComponent(sairPaginaButton)
                        .addGap(17, 17, 17))))
        );
        cabecalhoPanelLayout.setVerticalGroup(
            cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCabecalhoLabel)
                    .addComponent(sairPaginaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professorRadioButton)
                    .addComponent(alunoRadioButton)
                    .addComponent(coordenadorRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        criarContaBotton.setForeground(new java.awt.Color(255, 255, 255));
        criarContaBotton.setText("CRIAR CONTA");
        criarContaBotton.setCor(new java.awt.Color(36, 53, 61));
        criarContaBotton.setCorBorda(new java.awt.Color(255, 255, 255));
        criarContaBotton.setCorEntrou(new java.awt.Color(19, 176, 110));
        criarContaBotton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        criarContaBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaBottonActionPerformed(evt);
            }
        });

        identifiqueLabel1.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        identifiqueLabel1.setForeground(new java.awt.Color(0, 0, 0));
        identifiqueLabel1.setText("ou");

        entrarContaBotton.setBackground(new java.awt.Color(102, 102, 102));
        entrarContaBotton.setForeground(new java.awt.Color(255, 255, 255));
        entrarContaBotton.setText("ENTRE NA SUA CONTA");
        entrarContaBotton.setCor(new java.awt.Color(102, 102, 102));
        entrarContaBotton.setCorBorda(new java.awt.Color(255, 255, 255));
        entrarContaBotton.setCorEntrou(new java.awt.Color(19, 176, 110));
        entrarContaBotton.setCorSaiu(new java.awt.Color(102, 102, 102));
        entrarContaBotton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entrarContaBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarContaBottonActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout formularioGeralPanelLayout = new javax.swing.GroupLayout(formularioGeralPanel);
        formularioGeralPanel.setLayout(formularioGeralPanelLayout);
        formularioGeralPanelLayout.setHorizontalGroup(
            formularioGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabecalhoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioGeralPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(criarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(identifiqueLabel1)
                .addGap(18, 18, 18)
                .addComponent(entrarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
            .addGroup(formularioGeralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        formularioGeralPanelLayout.setVerticalGroup(
            formularioGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioGeralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalhoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formularioGeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identifiqueLabel1))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formularioGeralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formularioGeralPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //evento de mover a janela
    private void cabecalhoPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabecalhoPanelMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_cabecalhoPanelMousePressed

    private void cabecalhoPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabecalhoPanelMouseDragged
        this.setLocation(this.getX() + evt.getX() - mouseX, this.getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_cabecalhoPanelMouseDragged

    private void sairPaginaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairPaginaButtonActionPerformed
        mouseX = getX();
        mouseY = getY();
        this.dispose();
        novaGestaoContaUsuario = new GestaoContaUsuario();
        novaGestaoContaUsuario.setLocation(mouseX, mouseY);
        novaGestaoContaUsuario.setVisible(true);
    }//GEN-LAST:event_sairPaginaButtonActionPerformed

    private void sairPaginaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairPaginaButtonMouseEntered
        Color corSelecionado = new Color(89, 89, 89);
        sairPaginaButton.setForeground(corSelecionado);
    }//GEN-LAST:event_sairPaginaButtonMouseEntered

    private void sairPaginaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairPaginaButtonMouseExited
        sairPaginaButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_sairPaginaButtonMouseExited

    private void criarContaBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaBottonActionPerformed
        
        popUp = null;
        
        //gerarPopUp();
        
        if (popUp == null) {
            
            if(alunoRadioButton.isSelected() || professorRadioButton.isSelected()) {
                numeroMatricula++;
                popUp = new PopUp();
                popUp.MensagemFinal("Sua conta foi criada com sucesso! Sua matrícula é " + numeroMatricula + ".", this);
            } else {
                popUp = new PopUp();
                popUp.MensagemFinal("Sua conta foi criada com sucesso! Acesse o sistema.", this);
            }
            
        }
        
    }//GEN-LAST:event_criarContaBottonActionPerformed

    private void entrarContaBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarContaBottonActionPerformed
        this.dispose();
        novaGestaoContaUsuario = new GestaoContaUsuario();
        novaGestaoContaUsuario.setVisible(true);
    }//GEN-LAST:event_entrarContaBottonActionPerformed

    private void professorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorRadioButtonActionPerformed
        formularioProfessor = new CampoFormularioProfessor();
        jScrollPane1.setViewportView(formularioProfessor);
    }//GEN-LAST:event_professorRadioButtonActionPerformed

    private void alunoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoRadioButtonActionPerformed
        formularioProfessor = new CampoFormularioProfessor();
        jScrollPane1.setViewportView(formularioProfessor);
    }//GEN-LAST:event_alunoRadioButtonActionPerformed

    private void coordenadorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordenadorRadioButtonActionPerformed
        formularioCoordenador = new CampoFormularioCoordenador();
        jScrollPane1.setViewportView(formularioCoordenador);
    }//GEN-LAST:event_coordenadorRadioButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public FormularioContaUsuario(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioContaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alunoRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cabecalhoPanel;
    private javax.swing.JRadioButton coordenadorRadioButton;
    private _07gestaoacademica.CustomizacaoBotao criarContaBotton;
    private _07gestaoacademica.CustomizacaoBotao entrarContaBotton;
    private javax.swing.JPanel formularioGeralPanel;
    private javax.swing.JLabel identifiqueLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton professorRadioButton;
    private javax.swing.JButton sairPaginaButton;
    private javax.swing.JLabel tituloCabecalhoLabel;
    // End of variables declaration//GEN-END:variables
}
