package _07gestaoacademica;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author ravtec
 */
public class FormularioButton extends javax.swing.JPanel {

    public float corAlfa = 1f;
    private javax.swing.JLabel iconeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JLabel tituloLabel;
    
    public FormularioButton() {
        
        initComponents();
        
        jPanel1 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        iconeLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(176, 188, 190));

        tituloLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("hh");

        iconeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_07gestaoacademica/images/alunosP.png")));

        numeroLabel.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        numeroLabel.setForeground(new java.awt.Color(51, 51, 51));
        numeroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroLabel.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(numeroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(iconeLabel)
                .addGap(18, 18, 18)
                .addComponent(numeroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        
        addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseEntered(MouseEvent e) {
                jPanel1.setBackground(new Color(36, 53, 61));
                numeroLabel.setForeground(Color.WHITE);
                tituloLabel.setForeground(Color.WHITE);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jPanel1.setBackground(new Color(176, 188, 190));
                numeroLabel.setForeground(Color.BLACK);
                tituloLabel.setForeground(Color.BLACK);
            }
            
        });
        
    }
    
    public void mudarIcone(String localIcone) {
        iconeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(localIcone)));
    }
    
    public void mudarNumero(String numero) {
        numeroLabel.setText(numero);
    }
    
    public void mudarTexto(String novoTexto) {
        tituloLabel.setText(novoTexto);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}


