package _07gestaoacademica;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ruben-braga
 */
public class GestaoContaUsuario extends javax.swing.JFrame {

    FormularioContaUsuario gerarFormulario;
    DashboardCoordenador dashboardCoordenador;
    Icon mostrarIcon = new ImageIcon(getClass().getResource("/_07gestaoacademica/images/mostrar.png"));
    Icon ocultarIcon = new ImageIcon(getClass().getResource("/_07gestaoacademica/images/ocultar.png"));
    Icon iconeAtual = ocultarIcon;
    PopUp popUp;
    private final UsuarioZero alan = new UsuarioZero();
    
    
    public GestaoContaUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        BancoDeDados.cadastrarUsuario(alan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gestaoPanel = new javax.swing.JPanel();
        selecaoPanel = new javax.swing.JPanel();
        bemVindoLabel = new javax.swing.JLabel();
        identifiqueLabel = new javax.swing.JLabel();
        professorAlunoRadioButton = new javax.swing.JRadioButton();
        coordenadorRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        matriculaLabel = new javax.swing.JLabel();
        matriculaTextField = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        senhaPasswordField = new javax.swing.JPasswordField();
        entrarContaBotton = new _07gestaoacademica.CustomizacaoBotao();
        identifiqueLabel1 = new javax.swing.JLabel();
        novoCadastroBotton = new _07gestaoacademica.CustomizacaoBotao();
        mostrarSenhaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela inicial");
        setResizable(false);
        setSize(new java.awt.Dimension(700, 409));

        gestaoPanel.setBackground(new java.awt.Color(255, 255, 255));

        selecaoPanel.setBackground(new java.awt.Color(255, 255, 255));

        bemVindoLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bemVindoLabel.setForeground(new java.awt.Color(0, 0, 0));
        bemVindoLabel.setText("Bem vindo ao sistema!");

        identifiqueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        identifiqueLabel.setForeground(new java.awt.Color(0, 0, 0));
        identifiqueLabel.setText("Identifique-se:");

        professorAlunoRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(professorAlunoRadioButton);
        professorAlunoRadioButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        professorAlunoRadioButton.setForeground(new java.awt.Color(36, 53, 61));
        professorAlunoRadioButton.setSelected(true);
        professorAlunoRadioButton.setText("Sou Professor(a)/Aluno(a)");
        professorAlunoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorAlunoRadioButtonActionPerformed(evt);
            }
        });

        coordenadorRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(coordenadorRadioButton);
        coordenadorRadioButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        coordenadorRadioButton.setForeground(new java.awt.Color(36, 53, 61));
        coordenadorRadioButton.setText("Sou Coordenador(a)");
        coordenadorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordenadorRadioButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout selecaoPanelLayout = new javax.swing.GroupLayout(selecaoPanel);
        selecaoPanel.setLayout(selecaoPanelLayout);
        selecaoPanelLayout.setHorizontalGroup(
            selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bemVindoLabel)
                    .addGroup(selecaoPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(selecaoPanelLayout.createSequentialGroup()
                                .addComponent(professorAlunoRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(coordenadorRadioButton))
                            .addComponent(identifiqueLabel))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        selecaoPanelLayout.setVerticalGroup(
            selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bemVindoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identifiqueLabel)
                .addGap(18, 18, 18)
                .addGroup(selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professorAlunoRadioButton)
                    .addComponent(coordenadorRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        matriculaLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        matriculaLabel.setForeground(new java.awt.Color(0, 0, 0));
        matriculaLabel.setText("Digite sua Matrícula:");

        matriculaTextField.setBackground(new java.awt.Color(255, 255, 255));
        matriculaTextField.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        matriculaTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        senhaLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(0, 0, 0));
        senhaLabel.setText("Digite sua Senha:");

        senhaPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        senhaPasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        entrarContaBotton.setForeground(new java.awt.Color(255, 255, 255));
        entrarContaBotton.setText("ENTRAR");
        entrarContaBotton.setCor(new java.awt.Color(36, 53, 61));
        entrarContaBotton.setCorBorda(new java.awt.Color(255, 255, 255));
        entrarContaBotton.setCorEntrou(new java.awt.Color(19, 176, 110));
        entrarContaBotton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entrarContaBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarContaBottonActionPerformed(evt);
            }
        });

        identifiqueLabel1.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        identifiqueLabel1.setForeground(new java.awt.Color(0, 0, 0));
        identifiqueLabel1.setText("ou");

        novoCadastroBotton.setBackground(new java.awt.Color(102, 102, 102));
        novoCadastroBotton.setForeground(new java.awt.Color(255, 255, 255));
        novoCadastroBotton.setText("CADASTRE-SE");
        novoCadastroBotton.setCor(new java.awt.Color(102, 102, 102));
        novoCadastroBotton.setCorBorda(new java.awt.Color(255, 255, 255));
        novoCadastroBotton.setCorEntrou(new java.awt.Color(19, 176, 110));
        novoCadastroBotton.setCorSaiu(new java.awt.Color(102, 102, 102));
        novoCadastroBotton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        novoCadastroBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCadastroBottonActionPerformed(evt);
            }
        });

        mostrarSenhaButton.setBackground(new java.awt.Color(255, 255, 255));
        mostrarSenhaButton.setForeground(new java.awt.Color(255, 255, 255));
        mostrarSenhaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_07gestaoacademica/images/ocultar.png"))); // NOI18N
        mostrarSenhaButton.setBorder(null);
        mostrarSenhaButton.setBorderPainted(false);
        mostrarSenhaButton.setContentAreaFilled(false);
        mostrarSenhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gestaoPanelLayout = new javax.swing.GroupLayout(gestaoPanel);
        gestaoPanel.setLayout(gestaoPanelLayout);
        gestaoPanelLayout.setHorizontalGroup(
            gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestaoPanelLayout.createSequentialGroup()
                .addGroup(gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestaoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selecaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(gestaoPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gestaoPanelLayout.createSequentialGroup()
                                .addComponent(novoCadastroBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 89, Short.MAX_VALUE))
                            .addGroup(gestaoPanelLayout.createSequentialGroup()
                                .addGroup(gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entrarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(gestaoPanelLayout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(identifiqueLabel1)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(gestaoPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(gestaoPanelLayout.createSequentialGroup()
                                .addComponent(senhaLabel)
                                .addGap(205, 205, 205))
                            .addGroup(gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(gestaoPanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(matriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(matriculaLabel))
                            .addGroup(gestaoPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(senhaPasswordField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mostrarSenhaButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gestaoPanelLayout.setVerticalGroup(
            gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matriculaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(senhaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarSenhaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(entrarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(identifiqueLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novoCadastroBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarContaBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarContaBottonActionPerformed
        
        if(professorAlunoRadioButton.isSelected()) {
            
            boolean matriculaNum = matriculaTextField.getText().chars().allMatch(Character::isDigit);
            
            if(!matriculaNum || "".equals(matriculaTextField.getText())) {
                
                popUp = new PopUp();
                popUp.entradaConta("ERRO", "Campo de matrícula não preenchido, ou inválido.");
                
            } else if("".equals(String.valueOf(senhaPasswordField.getPassword()))) {
                
                popUp = new PopUp();
                popUp.campoNaoPreenchido("senha", senhaPasswordField);
                
            } else {
                
                BancoDeDados.loginProfessorAluno(Integer.parseInt(matriculaTextField.getText()), String.valueOf(senhaPasswordField.getPassword()));
                
                if (BancoDeDados.loginProfessorAluno(Integer.parseInt(matriculaTextField.getText()), String.valueOf(senhaPasswordField.getPassword())) == true) {
                    popUp = new PopUp();
                    popUp.entradaConta("SUCESSO", "Bem vindo!!!");
                } else {
                    popUp = new PopUp();
                    popUp.entradaConta("ERRO", "Operação mal sucedida.");
                }
                
            }
            
        } else {
            
            if("".equals(matriculaTextField.getText())) {
                
                popUp = new PopUp();
                popUp.entradaConta("ERRO", "Campo do nome de usuário não preenchido, ou inválido.");
                
            } else if("".equals(String.valueOf(senhaPasswordField.getPassword()))) {
                
                popUp = new PopUp();
                popUp.campoNaoPreenchido("senha", senhaPasswordField);
                
            } else {
                
                BancoDeDados.loginCoordenador(matriculaTextField.getText(), String.valueOf(senhaPasswordField.getPassword()));
            
                if(BancoDeDados.loginCoordenador(matriculaTextField.getText(), String.valueOf(senhaPasswordField.getPassword())) == true) {
                popUp = new PopUp();
                dashboardCoordenador = new DashboardCoordenador();
                dashboardCoordenador.setVisible(true);
                this.dispose();
                } else {
                    popUp = new PopUp();
                    popUp.entradaConta("ERRO", "Operação mal sucedida.");
                }
                
            }
            
        }
        
    }//GEN-LAST:event_entrarContaBottonActionPerformed

    private void novoCadastroBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoCadastroBottonActionPerformed
        gerarFormulario = new FormularioContaUsuario();
        gerarFormulario.setLocationRelativeTo(null);
        gerarFormulario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_novoCadastroBottonActionPerformed

    private void professorAlunoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorAlunoRadioButtonActionPerformed
        this.matriculaLabel.setText("Digite sua Matrícula:");
    }//GEN-LAST:event_professorAlunoRadioButtonActionPerformed

    private void coordenadorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordenadorRadioButtonActionPerformed
        this.matriculaLabel.setText("Digite seu nome de usuário:");
    }//GEN-LAST:event_coordenadorRadioButtonActionPerformed

    private void mostrarSenhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaButtonActionPerformed
        
        if(iconeAtual == ocultarIcon) {
            mostrarSenhaButton.setIcon(mostrarIcon);
            senhaPasswordField.setEchoChar((char) 0);
            iconeAtual = mostrarIcon;
        } else{
            mostrarSenhaButton.setIcon(ocultarIcon);
            senhaPasswordField.setEchoChar((char) '*');
            iconeAtual = ocultarIcon;
        }
        
    }//GEN-LAST:event_mostrarSenhaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestaoContaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bemVindoLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton coordenadorRadioButton;
    private _07gestaoacademica.CustomizacaoBotao entrarContaBotton;
    private javax.swing.JPanel gestaoPanel;
    private javax.swing.JLabel identifiqueLabel;
    private javax.swing.JLabel identifiqueLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel matriculaLabel;
    private javax.swing.JTextField matriculaTextField;
    private javax.swing.JButton mostrarSenhaButton;
    private _07gestaoacademica.CustomizacaoBotao novoCadastroBotton;
    private javax.swing.JRadioButton professorAlunoRadioButton;
    private javax.swing.JPanel selecaoPanel;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaPasswordField;
    // End of variables declaration//GEN-END:variables
}
