/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _07gestaoacademica;

/**
 *
 * @author ravtec
 */
public class GestaoContaUsuario extends javax.swing.JFrame {

    FormularioContaUsuario gerarFormulario;
    
    
    public GestaoContaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gestaoPanel = new javax.swing.JPanel();
        selecaoPanel = new javax.swing.JPanel();
        bemVindoLabel = new javax.swing.JLabel();
        identifiqueLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        criarContaBotton = new _07gestaoacademica.CustomizacaoBotao();
        identifiqueLabel1 = new javax.swing.JLabel();
        entrarContaBotton = new _07gestaoacademica.CustomizacaoBotao();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 409));

        gestaoPanel.setBackground(new java.awt.Color(255, 255, 255));

        selecaoPanel.setBackground(new java.awt.Color(255, 255, 255));

        bemVindoLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bemVindoLabel.setForeground(new java.awt.Color(0, 0, 0));
        bemVindoLabel.setText("Bem vindo ao sistema!");

        identifiqueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        identifiqueLabel.setForeground(new java.awt.Color(0, 0, 0));
        identifiqueLabel.setText("Identifique-se:");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(36, 53, 61));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Sou Professor(a)");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(36, 53, 61));
        jRadioButton2.setText("Sou Aluno(a)");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(36, 53, 61));
        jRadioButton3.setText("Sou Coordenador(a)");

        javax.swing.GroupLayout selecaoPanelLayout = new javax.swing.GroupLayout(selecaoPanel);
        selecaoPanel.setLayout(selecaoPanelLayout);
        selecaoPanelLayout.setHorizontalGroup(
            selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bemVindoLabel)
                    .addGroup(selecaoPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(selecaoPanelLayout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addComponent(identifiqueLabel)
                            .addComponent(jRadioButton3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selecaoPanelLayout.setVerticalGroup(
            selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bemVindoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identifiqueLabel)
                .addGap(18, 18, 18)
                .addGroup(selecaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        criarContaBotton.setForeground(new java.awt.Color(255, 255, 255));
        criarContaBotton.setText("CRIAR CONTA");
        criarContaBotton.setToolTipText("");
        criarContaBotton.setCor(new java.awt.Color(36, 53, 61));
        criarContaBotton.setCorBorda(new java.awt.Color(255, 255, 255));
        criarContaBotton.setCorEntrou(new java.awt.Color(19, 176, 110));
        criarContaBotton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        criarContaBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaBottonActionPerformed(evt);
            }
        });

        identifiqueLabel1.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        identifiqueLabel1.setForeground(new java.awt.Color(0, 0, 0));
        identifiqueLabel1.setText("ou");

        entrarContaBotton.setForeground(new java.awt.Color(255, 255, 255));
        entrarContaBotton.setText("ENTRAR NA SUA CONTA");
        entrarContaBotton.setToolTipText("");
        entrarContaBotton.setCor(new java.awt.Color(36, 53, 61));
        entrarContaBotton.setCorBorda(new java.awt.Color(255, 255, 255));
        entrarContaBotton.setCorEntrou(new java.awt.Color(19, 176, 110));
        entrarContaBotton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        entrarContaBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarContaBottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gestaoPanelLayout = new javax.swing.GroupLayout(gestaoPanel);
        gestaoPanel.setLayout(gestaoPanelLayout);
        gestaoPanelLayout.setHorizontalGroup(
            gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestaoPanelLayout.createSequentialGroup()
                .addGroup(gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestaoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selecaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(gestaoPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entrarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(gestaoPanelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(identifiqueLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gestaoPanelLayout.setVerticalGroup(
            gestaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(criarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(identifiqueLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entrarContaBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void criarContaBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaBottonActionPerformed
        gerarFormulario = new FormularioContaUsuario();
        gerarFormulario.setVisible(true);
    }//GEN-LAST:event_criarContaBottonActionPerformed

    private void entrarContaBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarContaBottonActionPerformed
        gerarFormulario = new FormularioContaUsuario();
        
    }//GEN-LAST:event_entrarContaBottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoContaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestaoContaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bemVindoLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private _07gestaoacademica.CustomizacaoBotao criarContaBotton;
    private _07gestaoacademica.CustomizacaoBotao entrarContaBotton;
    private javax.swing.JPanel gestaoPanel;
    private javax.swing.JLabel identifiqueLabel;
    private javax.swing.JLabel identifiqueLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPanel selecaoPanel;
    // End of variables declaration//GEN-END:variables
}
