package _07gestaoacademica;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.table.TableColumn;

public class ListagemDeTurma extends javax.swing.JFrame {

    //Atributos
    private int mouseX, mouseY;
    DashboardCoordenador voltarDashboardCoordenador;
    GestaoContaUsuario novaGestaoContaUsuario;
    ModeloTabelaTurma tableModel = new ModeloTabelaTurma();
    
    public ListagemDeTurma() {
        initComponents();
        setLocationRelativeTo(null);
        
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        tabelaTurma.setModel(tableModel);
        TableColumn colunaDosBotoes = tabelaTurma.getColumnModel().getColumn(3);
        colunaDosBotoes.setCellRenderer(new BotoesRenderer());
        colunaDosBotoes.setCellEditor(new BotoesListagemTurmaEditor(tabelaTurma, this, tableModel));
        limparCampoButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pesquisarTurmaButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cabecalhoPanel = new javax.swing.JPanel();
        sairPaginaButton = new javax.swing.JButton();
        botaoVoltarLabel = new javax.swing.JLabel();
        tituloDaPaginaLabel = new javax.swing.JLabel();
        criarNovaTurmaLabel = new _07gestaoacademica.CustomizacaoBotao();
        separador = new javax.swing.JSeparator();
        codigoTurmaLabel = new javax.swing.JLabel();
        campoDeCodigo = new _07gestaoacademica.CampoDeEscrita();
        disciplinaTurmaLabel = new javax.swing.JLabel();
        campoDisciplinaDaTurma = new _07gestaoacademica.CampoDeEscrita();
        professorTurmaLabel = new javax.swing.JLabel();
        campoProfessorTurma = new _07gestaoacademica.CampoDeEscrita();
        limparCampoButton = new _07gestaoacademica.CustomizacaoBotao();
        pesquisarTurmaButton = new _07gestaoacademica.CustomizacaoBotao();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTurma = new _07gestaoacademica.JTablePersonalizada();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabecalhoPanel.setBackground(new java.awt.Color(204, 204, 204));
        cabecalhoPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cabecalhoPanelMouseDragged(evt);
            }
        });
        cabecalhoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cabecalhoPanelMousePressed(evt);
            }
        });

        sairPaginaButton.setBackground(new java.awt.Color(255, 255, 255));
        sairPaginaButton.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        sairPaginaButton.setForeground(new java.awt.Color(0, 0, 0));
        sairPaginaButton.setText("X");
        sairPaginaButton.setBorder(null);
        sairPaginaButton.setContentAreaFilled(false);
        sairPaginaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sairPaginaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairPaginaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairPaginaButtonMouseExited(evt);
            }
        });
        sairPaginaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairPaginaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cabecalhoPanelLayout = new javax.swing.GroupLayout(cabecalhoPanel);
        cabecalhoPanel.setLayout(cabecalhoPanelLayout);
        cabecalhoPanelLayout.setHorizontalGroup(
            cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sairPaginaButton)
                .addGap(18, 18, 18))
        );
        cabecalhoPanelLayout.setVerticalGroup(
            cabecalhoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sairPaginaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(cabecalhoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        botaoVoltarLabel.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        botaoVoltarLabel.setForeground(new java.awt.Color(102, 102, 102));
        botaoVoltarLabel.setText("←");
        botaoVoltarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVoltarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVoltarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoVoltarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoVoltarLabelMouseExited(evt);
            }
        });
        jPanel1.add(botaoVoltarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, -1, 30));

        tituloDaPaginaLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        tituloDaPaginaLabel.setForeground(new java.awt.Color(30, 30, 30));
        tituloDaPaginaLabel.setText("Listagem de Turmas");
        jPanel1.add(tituloDaPaginaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 58, 290, -1));

        criarNovaTurmaLabel.setForeground(new java.awt.Color(255, 255, 255));
        criarNovaTurmaLabel.setText("Nova Turma");
        criarNovaTurmaLabel.setCor(new java.awt.Color(36, 53, 61));
        criarNovaTurmaLabel.setCorBorda(new java.awt.Color(255, 255, 255));
        criarNovaTurmaLabel.setCorEntrou(new java.awt.Color(19, 176, 110));
        criarNovaTurmaLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        criarNovaTurmaLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarNovaTurmaLabelActionPerformed(evt);
            }
        });
        jPanel1.add(criarNovaTurmaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, 34));

        separador.setForeground(new java.awt.Color(234, 234, 234));
        jPanel1.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 710, 10));

        codigoTurmaLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        codigoTurmaLabel.setForeground(new java.awt.Color(0, 0, 0));
        codigoTurmaLabel.setText("Código");
        jPanel1.add(codigoTurmaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        campoDeCodigo.setText("");
        campoDeCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoDeCodigoKeyPressed(evt);
            }
        });
        jPanel1.add(campoDeCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, -1));

        disciplinaTurmaLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        disciplinaTurmaLabel.setForeground(new java.awt.Color(0, 0, 0));
        disciplinaTurmaLabel.setText("Disciplina");
        jPanel1.add(disciplinaTurmaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        campoDisciplinaDaTurma.setText("");
        campoDisciplinaDaTurma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoDisciplinaDaTurmaKeyPressed(evt);
            }
        });
        jPanel1.add(campoDisciplinaDaTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 150, -1));

        professorTurmaLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        professorTurmaLabel.setForeground(new java.awt.Color(0, 0, 0));
        professorTurmaLabel.setText("Professor");
        jPanel1.add(professorTurmaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        campoProfessorTurma.setText("");
        campoProfessorTurma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoProfessorTurmaKeyPressed(evt);
            }
        });
        jPanel1.add(campoProfessorTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 180, -1));

        limparCampoButton.setBackground(new java.awt.Color(188, 188, 188));
        limparCampoButton.setForeground(new java.awt.Color(255, 255, 255));
        limparCampoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_07gestaoacademica/images/sairP.png"))); // NOI18N
        limparCampoButton.setCor(new java.awt.Color(188, 188, 188));
        limparCampoButton.setCorBorda(new java.awt.Color(255, 255, 255));
        limparCampoButton.setCorClicou(new java.awt.Color(117, 146, 153));
        limparCampoButton.setCorEntrou(new java.awt.Color(142, 159, 163));
        limparCampoButton.setCorSaiu(new java.awt.Color(188, 188, 188));
        limparCampoButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        limparCampoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCampoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(limparCampoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 30, 30));

        pesquisarTurmaButton.setForeground(new java.awt.Color(255, 255, 255));
        pesquisarTurmaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_07gestaoacademica/images/lupaB.png"))); // NOI18N
        pesquisarTurmaButton.setCor(new java.awt.Color(76, 95, 99));
        pesquisarTurmaButton.setCorBorda(new java.awt.Color(255, 255, 255));
        pesquisarTurmaButton.setCorClicou(new java.awt.Color(117, 146, 153));
        pesquisarTurmaButton.setCorEntrou(new java.awt.Color(87, 123, 132));
        pesquisarTurmaButton.setCorSaiu(new java.awt.Color(76, 95, 99));
        pesquisarTurmaButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pesquisarTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarTurmaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pesquisarTurmaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 30, 30));

        jScrollPane1.setBorder(null);

        tabelaTurma.setBackground(new java.awt.Color(255, 255, 255));
        tabelaTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaTurma.setGridColor(new java.awt.Color(51, 51, 51));
        tabelaTurma.setSelectionBackground(new java.awt.Color(19, 176, 110));
        jScrollPane1.setViewportView(tabelaTurma);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 190, 660, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairPaginaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairPaginaButtonMouseEntered
        Color corSelecionado = new Color(89, 89, 89);
        sairPaginaButton.setForeground(corSelecionado);
    }//GEN-LAST:event_sairPaginaButtonMouseEntered

    private void sairPaginaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairPaginaButtonMouseExited
        sairPaginaButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_sairPaginaButtonMouseExited

    private void sairPaginaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairPaginaButtonActionPerformed
        novaGestaoContaUsuario = new GestaoContaUsuario();
        novaGestaoContaUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairPaginaButtonActionPerformed

    private void cabecalhoPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabecalhoPanelMouseDragged
        this.setLocation(this.getX() + evt.getX() - mouseX, this.getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_cabecalhoPanelMouseDragged

    private void cabecalhoPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabecalhoPanelMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_cabecalhoPanelMousePressed

    private void botaoVoltarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarLabelMouseClicked
        voltarDashboardCoordenador = new DashboardCoordenador();
        voltarDashboardCoordenador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarLabelMouseClicked

    private void botaoVoltarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarLabelMouseEntered
        botaoVoltarLabel.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_botaoVoltarLabelMouseEntered

    private void botaoVoltarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVoltarLabelMouseExited
        botaoVoltarLabel.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_botaoVoltarLabelMouseExited

    private void criarNovaTurmaLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarNovaTurmaLabelActionPerformed
        
        CadastroNovaTurma cadastroNovaTurma = new CadastroNovaTurma();
        cadastroNovaTurma.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_criarNovaTurmaLabelActionPerformed

    private void campoDeCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDeCodigoKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        pesquisarTurmaButtonActionPerformed(null);

    }//GEN-LAST:event_campoDeCodigoKeyPressed

    private void campoDisciplinaDaTurmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDisciplinaDaTurmaKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        pesquisarTurmaButtonActionPerformed(null);

    }//GEN-LAST:event_campoDisciplinaDaTurmaKeyPressed

    private void campoProfessorTurmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoProfessorTurmaKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        pesquisarTurmaButtonActionPerformed(null);

    }//GEN-LAST:event_campoProfessorTurmaKeyPressed

    private void limparCampoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCampoButtonActionPerformed

        campoDeCodigo.setText("");
        campoDisciplinaDaTurma.setText("");
        campoProfessorTurma.setText("");
        pesquisarTurmaButton.doClick();

    }//GEN-LAST:event_limparCampoButtonActionPerformed

    private void pesquisarTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarTurmaButtonActionPerformed

        

    }//GEN-LAST:event_pesquisarTurmaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemDeTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemDeTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemDeTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemDeTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemDeTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoVoltarLabel;
    private javax.swing.JPanel cabecalhoPanel;
    private _07gestaoacademica.CampoDeEscrita campoDeCodigo;
    private _07gestaoacademica.CampoDeEscrita campoDisciplinaDaTurma;
    private _07gestaoacademica.CampoDeEscrita campoProfessorTurma;
    private javax.swing.JLabel codigoTurmaLabel;
    private _07gestaoacademica.CustomizacaoBotao criarNovaTurmaLabel;
    private javax.swing.JLabel disciplinaTurmaLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private _07gestaoacademica.CustomizacaoBotao limparCampoButton;
    private _07gestaoacademica.CustomizacaoBotao pesquisarTurmaButton;
    private javax.swing.JLabel professorTurmaLabel;
    private javax.swing.JButton sairPaginaButton;
    private javax.swing.JSeparator separador;
    private _07gestaoacademica.JTablePersonalizada tabelaTurma;
    private javax.swing.JLabel tituloDaPaginaLabel;
    // End of variables declaration//GEN-END:variables
}
